"""Add permissions to Role

Revision ID: 539dab5ccfdf
Revises: 8e95d4ad148d
Create Date: 2026-04-18 22:36:57.203219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539dab5ccfdf'
down_revision = '8e95d4ad148d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=False)
        batch_op.drop_column('permissions')
        batch_op.drop_column('default')

    # ### end Alembic commands ###
